server:
  port: 8081
  
spring:
  application:
    name: third1-application
  # h2 配置  
  datasource:
    url: jdbc:h2:file:./third1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:schema.sql 
  # 开启H2 GUI    
  h2:
    console:
      enabled: true  